language: php
php:
  - 5.6
  - 7

services:
  - redis-server

env:
  global:
    - BRANCH=master
    - REPO=oc
  matrix:
    - DB=mysql

matrix:
  include:
    - php: 5.6
      env: DB=sqlite
    - php: 5.6
      env: DB=pgsql
    - php: 5.6
      env: DB=mysql BRANCH=stable8
    - php: 5.6
      env: DB=mysql BRANCH=stable8.1
    - php: 5.6
      env: DB=mysql BRANCH=stable8.2
    - php: 5.6
      env: DB=mysql BRANCH=stable9
    - php: 5.6
      env: DB=mysql BRANCH=stable9.1
    - php: 5.4
      env: DB=mysql BRANCH=stable9.1
    - php: 5.5
      env: DB=mysql BRANCH=stable9.1
    - php: 5.6
      env: DB=mysql BRANCH=stable9 REPO=nc
    - php: 5.6
      env: DB=mysql BRANCH=stable10 REPO=nc
    - php: 5.6
      env: DB=mysql BRANCH=master REPO=nc



install: ./tests/travis/install-$REPO-$BRANCH.sh

# Note the install script should make sure we are in the apps/ojsxc directory
script:
  - composer install
  - phpunit -c phpunit.xml
  - phpunit -c phpunit.integration.xml
  - cat ../../data/owncloud.log || cat ../../data/nextcloud.log
